[nitpick.files.absent]
"requirements.txt" = "Install poetry, run 'poetry init' to create pyproject.toml, and move dependencies to it"
"Pipfile" = "Use pyproject.toml instead"
"Pipfile.lock" = "Use pyproject.toml instead"

".isort.cfg" = "Move values to pyproject.toml, section [tool.isort]"
".flake8" = "Move values to pyproject.toml, section [tool.flake8]"
"mypy.ini" = "Move values to pyproject.toml, section [tool.mypy]"

".pyup.yml" = "Configure your CI with safety instead: https://github.com/pyupio/safety#using-safety-with-a-ci-service"


[nitpick.files.present]
#".editorconfig" = "A project should have an editor configuration"
"CHANGELOG.md" = "A project should have `CHANGELOG.md`"
"README.md" = "A project should have `README.md`"
".gitignore" = "A project should have `.gitignore` file"
