[nitpick]
minimum_version = "0.29.0"

[nitpick.styles]
include = [
  "github://CaptainBloodborne/python-style/poetry.toml",
  "github://CaptainBloodborne/python-style/ruff.toml",
  "github://CaptainBloodborne/python-style/mypy.toml",
  "github://CaptainBloodborne/python-style/file-structure.toml"
]
