[nitpick]
minimum_version = "0.34.0"

[nitpick.styles]
include = [
  "https://github.com/CaptainBloodborne/python-style/blob/master/styles/poetry.toml",
  "https://github.com/CaptainBloodborne/python-style/blob/master/styles/ruff.toml",
  "https://github.com/CaptainBloodborne/python-style/blob/master/styles/mypy.toml",
  "https://github.com/CaptainBloodborne/python-style/blob/master/styles/file-structure.toml"
]
